name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.INSTANCE_ADDRESS }}
          username: ${{ secrets.INSTANCE_USERNAME }}
          key: ${{ secrets.INSTANCE_SSH_KEY }}
          script: docker login -u AWS -p $(aws ecr get-login-password --region us-east-2) ${{ secrets.ECR_REPOSITORY }} && docker run --env-file .env -p '3003:80' -d ${{ secrets.ECR_REPOSITORY }}/node-nls:latest npm run start
